# Generated by Django 5.1.1 on 2024-10-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='hospital.location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='hospital.location')),
            ],
        ),
    ]
